### ISSUE TITLE
Not sure how to install

### ISSUE THREAD

**Issue by dgleba** [nextcloud/files_texteditor#971]
Question:

Am I doing this right? What should the result be?
Many thanks for considering my request.

Detail:

I have done the following. It shows in apps - `Plain text editor`. see next pic.

![Image](https://github.com/user-attachments/assets/d5b0088e-d7ed-45f4-9bf0-982f95e1fb4e)

When I press `new text file` I see what is in next pic. But, I don't know if that is files_texteditor.

![Image](https://github.com/user-attachments/assets/6d6be3f9-3731-468b-ab4c-ac4fefef8457)

I followed this. https://chatgpt.com/share/67fc6dae-7d6c-8013-b9c2-059024e48aeb

![Image](https://github.com/user-attachments/assets/789a7dd6-b5b6-4f41-8eaa-5c2b4bd90c37)

docker-compose.yml
```
  nc:
    # http://192.168.88.103:6219
    image: nextcloud:apache
    restart: always
    ports:
      - 6219:80
    env_file:
      - .env
    volumes:
      - nc_data:/var/www/html
      - ./customapps:/var/www/html/custom_apps 
```
